version: "3.9"

networks:
  app-network:
    driver: bridge

services:
  # Add the Next.js App service
  app:
    build:
      context: ../ # Build from the root of the project
      dockerfile: dockerfile
    container_name: nextjs-app
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - loki
    environment:
      # This URL is used by the rate-limiter in your code
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_URL=http://localhost:3000
      - AUTH_TRUST_HOST=true
      - NEXTAUTH_SECRET=1hIYTnWU1FluFJPhzTLRP/6JQDJtR5mgN918XREx4x0=
    networks:
      - app-network

  # --- Infrastructure Services from before ---
  redis:
    image: "redis:7-alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app-network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasources.yml
    networks:
      - app-network